# Generated by Django 2.2.6 on 2019-10-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_informacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nic',
            name='numero',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
