# Generated by Django 2.2.1 on 2019-10-09 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191009_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='adm',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emailInstitucional',
        ),
        migrations.RemoveField(
            model_name='user',
            name='matricula',
        ),
        migrations.RemoveField(
            model_name='user',
            name='orgao',
        ),
        migrations.RemoveField(
            model_name='user',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telContato',
        ),
    ]
